DTC_DB = {
    "P0001": {"d": "Fuel Volume Regulator Control Circuit/Open", "s": "moderate", "sys": "Fuel"},
    "P0002": {"d": "Fuel Volume Regulator Control Circuit Range/Performance", "s": "moderate", "sys": "Fuel"},
    "P0010": {"d": "A Camshaft Position Actuator Circuit (Bank 1)", "s": "moderate", "sys": "Engine"},
    "P0011": {"d": "A Camshaft Position - Timing Over-Advanced (Bank 1)", "s": "moderate", "sys": "Engine"},
    "P0030": {"d": "HO2S Heater Control Circuit (Bank 1 Sensor 1)", "s": "low", "sys": "Emissions"},
    "P0031": {"d": "HO2S Heater Control Circuit Low (Bank 1 Sensor 1)", "s": "low", "sys": "Emissions"},
    "P0032": {"d": "HO2S Heater Control Circuit High (Bank 1 Sensor 1)", "s": "low", "sys": "Emissions"},
    "P0036": {"d": "HO2S Heater Control Circuit (Bank 1 Sensor 2)", "s": "low", "sys": "Emissions"},
    "P0100": {"d": "Mass or Volume Air Flow Circuit Malfunction", "s": "moderate", "sys": "Air Intake"},
    "P0101": {"d": "MAF Circuit Range/Performance", "s": "moderate", "sys": "Air Intake"},
    "P0102": {"d": "MAF Circuit Low Input", "s": "moderate", "sys": "Air Intake"},
    "P0103": {"d": "MAF Circuit High Input", "s": "moderate", "sys": "Air Intake"},
    "P0106": {"d": "MAP/Barometric Pressure Circuit Range/Performance", "s": "moderate", "sys": "Air Intake"},
    "P0107": {"d": "MAP Circuit Low Input", "s": "moderate", "sys": "Air Intake"},
    "P0108": {"d": "MAP Circuit High Input", "s": "moderate", "sys": "Air Intake"},
    "P0113": {"d": "Intake Air Temperature Circuit High Input", "s": "low", "sys": "Air Intake"},
    "P0115": {"d": "Engine Coolant Temperature Circuit Malfunction", "s": "severe", "sys": "Cooling"},
    "P0116": {"d": "Engine Coolant Temperature Circuit Range/Performance", "s": "severe", "sys": "Cooling"},
    "P0117": {"d": "Engine Coolant Temperature Circuit Low Input", "s": "severe", "sys": "Cooling"},
    "P0118": {"d": "Engine Coolant Temperature Circuit High Input", "s": "severe", "sys": "Cooling"},
    "P0120": {"d": "Throttle/Pedal Position Sensor/Switch A Circuit Malfunction", "s": "severe", "sys": "Throttle"},
    "P0121": {"d": "Throttle/Pedal Position Sensor/Switch A Circuit Range/Performance", "s": "severe", "sys": "Throttle"},
    "P0122": {"d": "Throttle/Pedal Position Sensor/Switch A Circuit Low Input", "s": "severe", "sys": "Throttle"},
    "P0123": {"d": "Throttle/Pedal Position Sensor/Switch A Circuit High Input", "s": "severe", "sys": "Throttle"},
    "P0130": {"d": "O2 Sensor Circuit Malfunction (Bank 1 Sensor 1)", "s": "moderate", "sys": "Emissions"},
    "P0131": {"d": "O2 Sensor Circuit Low Voltage (Bank 1 Sensor 1)", "s": "moderate", "sys": "Emissions"},
    "P0132": {"d": "O2 Sensor Circuit High Voltage (Bank 1 Sensor 1)", "s": "moderate", "sys": "Emissions"},
    "P0133": {"d": "O2 Sensor Circuit Slow Response (Bank 1 Sensor 1)", "s": "low", "sys": "Emissions"},
    "P0134": {"d": "O2 Sensor Circuit No Activity Detected (Bank 1 Sensor 1)", "s": "moderate", "sys": "Emissions"},
    "P0135": {"d": "O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 1)", "s": "low", "sys": "Emissions"},
    "P0171": {"d": "System Too Lean (Bank 1)", "s": "moderate", "sys": "Fuel"},
    "P0172": {"d": "System Too Rich (Bank 1)", "s": "moderate", "sys": "Fuel"},
    "P0174": {"d": "System Too Lean (Bank 2)", "s": "moderate", "sys": "Fuel"},
    "P0175": {"d": "System Too Rich (Bank 2)", "s": "moderate", "sys": "Fuel"},
    "P0201": {"d": "Injector Circuit/Open - Cylinder 1", "s": "severe", "sys": "Fuel"},
    "P0202": {"d": "Injector Circuit/Open - Cylinder 2", "s": "severe", "sys": "Fuel"},
    "P0203": {"d": "Injector Circuit/Open - Cylinder 3", "s": "severe", "sys": "Fuel"},
    "P0204": {"d": "Injector Circuit/Open - Cylinder 4", "s": "severe", "sys": "Fuel"},
    "P0300": {"d": "Random/Multiple Cylinder Misfire Detected", "s": "severe", "sys": "Ignition"},
    "P0301": {"d": "Cylinder 1 Misfire Detected", "s": "severe", "sys": "Ignition"},
    "P0302": {"d": "Cylinder 2 Misfire Detected", "s": "severe", "sys": "Ignition"},
    "P0303": {"d": "Cylinder 3 Misfire Detected", "s": "severe", "sys": "Ignition"},
    "P0304": {"d": "Cylinder 4 Misfire Detected", "s": "severe", "sys": "Ignition"},
    "P0305": {"d": "Cylinder 5 Misfire Detected", "s": "severe", "sys": "Ignition"},
    "P0306": {"d": "Cylinder 6 Misfire Detected", "s": "severe", "sys": "Ignition"},
    "P0315": {"d": "Crankshaft Position System Variation Not Learned", "s": "moderate", "sys": "Engine"},
    "P0325": {"d": "Knock Sensor 1 Circuit Malfunction (Bank 1)", "s": "moderate", "sys": "Engine"},
    "P0335": {"d": "Crankshaft Position Sensor A Circuit Malfunction", "s": "severe", "sys": "Engine"},
    "P0336": {"d": "Crankshaft Position Sensor A Circuit Range/Performance", "s": "severe", "sys": "Engine"},
    "P0340": {"d": "Camshaft Position Sensor Circuit Malfunction", "s": "severe", "sys": "Engine"},
    "P0341": {"d": "Camshaft Position Sensor Circuit Range/Performance", "s": "severe", "sys": "Engine"},
    "P0351": {"d": "Ignition Coil A Primary/Secondary Circuit Malfunction", "s": "severe", "sys": "Ignition"},
    "P0352": {"d": "Ignition Coil B Primary/Secondary Circuit Malfunction", "s": "severe", "sys": "Ignition"},
    "P0353": {"d": "Ignition Coil C Primary/Secondary Circuit Malfunction", "s": "severe", "sys": "Ignition"},
    "P0354": {"d": "Ignition Coil D Primary/Secondary Circuit Malfunction", "s": "severe", "sys": "Ignition"},
    "P0401": {"d": "EGR Flow Insufficient Detected", "s": "moderate", "sys": "Emissions"},
    "P0402": {"d": "EGR Flow Excessive Detected", "s": "moderate", "sys": "Emissions"},
    "P0420": {"d": "Catalyst System Efficiency Below Threshold (Bank 1)", "s": "moderate", "sys": "Emissions"},
    "P0430": {"d": "Catalyst System Efficiency Below Threshold (Bank 2)", "s": "moderate", "sys": "Emissions"},
    "P0440": {"d": "Evaporative Emission Control System Malfunction", "s": "low", "sys": "Emissions"},
    "P0441": {"d": "Evaporative Emission Control System Incorrect Purge Flow", "s": "low", "sys": "Emissions"},
    "P0442": {"d": "Evap System Leak Detected (small leak)", "s": "low", "sys": "Emissions"},
    "P0455": {"d": "Evap System Leak Detected (gross leak)", "s": "low", "sys": "Emissions"},
    "P0456": {"d": "Evap System Leak Detected (very small leak)", "s": "low", "sys": "Emissions"},
    "P0500": {"d": "Vehicle Speed Sensor Malfunction", "s": "moderate", "sys": "Transmission"},
    "P0505": {"d": "Idle Control System Malfunction", "s": "moderate", "sys": "Engine"},
    "P0562": {"d": "System Voltage Low", "s": "moderate", "sys": "Electrical"},
    "P0563": {"d": "System Voltage High", "s": "moderate", "sys": "Electrical"},
    "P0600": {"d": "Serial Communication Link Malfunction", "s": "severe", "sys": "ECU"},
    "P0603": {"d": "Internal Control Module Keep Alive Memory Error", "s": "moderate", "sys": "ECU"},
    "P0700": {"d": "Transmission Control System Malfunction", "s": "severe", "sys": "Transmission"},
    "P0705": {"d": "Transmission Range Sensor Circuit Malfunction (PRNDL Input)", "s": "moderate", "sys": "Transmission"},
    "P0715": {"d": "Input/Turbine Speed Sensor Circuit Malfunction", "s": "severe", "sys": "Transmission"},
    "P0720": {"d": "Output Speed Sensor Circuit Malfunction", "s": "severe", "sys": "Transmission"},
    "P0740": {"d": "Torque Converter Clutch Circuit Malfunction", "s": "moderate", "sys": "Transmission"},
    "P0750": {"d": "Shift Solenoid A Malfunction", "s": "severe", "sys": "Transmission"},
    "P0755": {"d": "Shift Solenoid B Malfunction", "s": "severe", "sys": "Transmission"},
    "P0760": {"d": "Shift Solenoid C Malfunction", "s": "severe", "sys": "Transmission"},
    "B1200": {"d": "Climate Control Pushbutton Circuit Failure", "s": "low", "sys": "Body"},
    "B1231": {"d": "Crash Data Memory Full", "s": "severe", "sys": "Safety"},
    "B1317": {"d": "Battery Voltage High", "s": "moderate", "sys": "Electrical"},
    "B1318": {"d": "Battery Voltage Low", "s": "moderate", "sys": "Electrical"},
    "B1342": {"d": "ECU Is Defective", "s": "severe", "sys": "ECU"},
    "B2293": {"d": "Occupant Classification System Fault", "s": "severe", "sys": "Safety"},
    "C1201": {"d": "ABS Inlet Valve Coil LF Circuit Short To Ground", "s": "severe", "sys": "Brakes"},
    "C1233": {"d": "Speed Wheel LF Input Signal Missing", "s": "severe", "sys": "ABS"},
    "C1234": {"d": "Speed Wheel RF Input Signal Missing", "s": "severe", "sys": "ABS"},
    "C1235": {"d": "Speed Wheel LR Input Signal Missing", "s": "severe", "sys": "ABS"},
    "C1236": {"d": "Speed Wheel RR Input Signal Missing", "s": "severe", "sys": "ABS"},
    "C1708": {"d": "Steering Angle Sensor Circuit Failure", "s": "moderate", "sys": "Steering"},
    "C1955": {"d": "Steering Angle Sensor Circuit Malfunction", "s": "moderate", "sys": "Steering"},
    "C1970": {"d": "Brake Pedal Position Switch Circuit Failure", "s": "severe", "sys": "Brakes"},
    "U0100": {"d": "Lost Communication With ECM/PCM", "s": "severe", "sys": "Network"},
    "U0101": {"d": "Lost Communication With TCM", "s": "severe", "sys": "Network"},
    "U0121": {"d": "Lost Communication With ABS Control Module", "s": "severe", "sys": "Network"},
    "U0140": {"d": "Lost Communication With Body Control Module", "s": "severe", "sys": "Network"},
    "U0401": {"d": "Invalid Data Received From ECM/PCM", "s": "severe", "sys": "Network"},
    "U0415": {"d": "Invalid Data Received From ABS Control Module", "s": "severe", "sys": "Network"},
    "U0422": {"d": "Invalid Data Received From Body Control Module", "s": "severe", "sys": "Network"},
    "U1000": {"d": "Class 2 Communication Network Malfunction", "s": "severe", "sys": "Network"},
    "P2004": {"d": "Intake Manifold Runner Control Stuck Open (Bank 1)", "s": "moderate", "sys": "Air Intake"},
    "P2005": {"d": "Intake Manifold Runner Control Stuck Open (Bank 2)", "s": "moderate", "sys": "Air Intake"},
    "P2006": {"d": "Intake Manifold Runner Control Stuck Closed (Bank 1)", "s": "moderate", "sys": "Air Intake"},
    "P2007": {"d": "Intake Manifold Runner Control Stuck Closed (Bank 2)", "s": "moderate", "sys": "Air Intake"},
    "P2096": {"d": "Post Catalyst Fuel Trim System Too Lean (Bank 1)", "s": "moderate", "sys": "Emissions"},
    "P2097": {"d": "Post Catalyst Fuel Trim System Too Rich (Bank 1)", "s": "moderate", "sys": "Emissions"},
    "P2100": {"d": "Throttle Actuator Control Motor Circuit/Open", "s": "severe", "sys": "Throttle"},
    "P2101": {"d": "Throttle Actuator Control Motor Circuit Range/Performance", "s": "severe", "sys": "Throttle"},
    "P2106": {"d": "Throttle Actuator Control System - Forced Limited Power", "s": "severe", "sys": "Throttle"},
    "P2110": {"d": "Throttle Actuator Control System - Forced Limited RPM", "s": "moderate", "sys": "Throttle"},
    "P2111": {"d": "Throttle Actuator Control System - Stuck Open", "s": "severe", "sys": "Throttle"},
    "P2112": {"d": "Throttle Actuator Control System - Stuck Closed", "s": "severe", "sys": "Throttle"},
    "P2135": {"d": "Throttle/Pedal Position Sensor/Switch A/B Voltage Correlation", "s": "severe", "sys": "Throttle"},
    "P2195": {"d": "O2 Sensor Signal Stuck Lean (Bank 1 Sensor 1)", "s": "moderate", "sys": "Fuel"},
    "P2196": {"d": "O2 Sensor Signal Stuck Rich (Bank 1 Sensor 1)", "s": "moderate", "sys": "Fuel"},
    "P2503": {"d": "Charging System Voltage Low", "s": "moderate", "sys": "Electrical"},
    "P2504": {"d": "Charging System Voltage High", "s": "moderate", "sys": "Electrical"},
    "P2610": {"d": "ECM/PCM Internal Engine Off Timer Performance", "s": "moderate", "sys": "ECU"},
}

REPAIR_GUIDE = {
    "P0171": {"parts": ["O2 sensor", "MAF sensor"], "causes": ["Vacuum leak", "Dirty MAF", "Weak fuel pump"]},
    "P0172": {"parts": ["O2 sensor", "Fuel pressure regulator"], "causes": ["Leaking injector", "Faulty MAF", "High fuel pressure"]},
    "P0300": {"parts": ["Spark plugs", "Coil packs", "Fuel injectors"], "causes": ["Worn plugs", "Clogged injector", "Bad fuel"]},
    "P0301": {"parts": ["Spark plug #1", "Coil #1", "Injector #1"], "causes": ["Worn plug", "Bad coil", "Clogged injector"]},
    "P0302": {"parts": ["Spark plug #2", "Coil #2", "Injector #2"], "causes": ["Worn plug", "Bad coil", "Clogged injector"]},
    "P0303": {"parts": ["Spark plug #3", "Coil #3", "Injector #3"], "causes": ["Worn plug", "Bad coil", "Clogged injector"]},
    "P0304": {"parts": ["Spark plug #4", "Coil #4", "Injector #4"], "causes": ["Worn plug", "Bad coil", "Clogged injector"]},
    "P0305": {"parts": ["Spark plug #5", "Coil #5", "Injector #5"], "causes": ["Worn plug", "Bad coil", "Clogged injector"]},
    "P0306": {"parts": ["Spark plug #6", "Coil #6", "Injector #6"], "causes": ["Worn plug", "Bad coil", "Clogged injector"]},
    "P0420": {"parts": ["Catalytic converter", "O2 sensors"], "causes": ["Aged cat", "Oil burning", "Rich mixture"]},
    "P0430": {"parts": ["Catalytic converter (Bank 2)", "O2 sensors"], "causes": ["Aged cat", "Oil burning", "Rich mixture"]},
    "P0401": {"parts": ["EGR valve", "EGR passages"], "causes": ["Carbon buildup", "Faulty EGR valve", "Blocked passages"]},
    "P0115": {"parts": ["ECT sensor", "Thermostat"], "causes": ["Bad sensor", "Stuck thermostat", "Low coolant"]},
    "P0130": {"parts": ["Upstream O2 sensor"], "causes": ["Sensor aging", "Heater failure", "Wiring issue"]},
    "P0562": {"parts": ["Alternator", "Battery", "Voltage regulator"], "causes": ["Weak alternator", "Bad battery", "Loose belt"]},
    "P0700": {"parts": ["Transmission fluid", "TCM", "Solenoids"], "causes": ["Low fluid", "Bad solenoid", "Internal wear"]},
    "P0335": {"parts": ["Crankshaft position sensor"], "causes": ["Sensor failure", "Wiring damage", "Timing issue"]},
    "P0340": {"parts": ["Camshaft position sensor"], "causes": ["Sensor failure", "Timing belt/chain", "Wiring issue"]},
    "P0500": {"parts": ["Vehicle speed sensor", "Wiring"], "causes": ["Sensor failure", "Damaged wiring", "ABS issue"]},
}
